- hosts: all  # Host or Group of Selections
  become: true
  vars:
    ansible_ssh_user: ec2-user 
    ansible_ssh_private_key_file: ~/linux-training.pem
  tasks:
  - name: Install amz epel 
    yum: name=* state=latest  
  - name: Start amazon-linux-extra
    shell: amazon-linux-extras install epel -y
  - name: Install amz epel 
    yum: name=stress state=present  
  